/* THIS FILE IS AUTO-GENERATED BY scripts/generate-geojson-registry.js */
/* Do not edit by hand. */

import type { Feature, FeatureCollection, Geometry } from "geojson"

import address from "@/assets/maps/imdf/address.json";
import interact_rooms_1F from "@/assets/maps/imdf/interact/rooms/1F.json";
import interact_rooms_2F from "@/assets/maps/imdf/interact/rooms/2F.json";
import interact_surface_1F from "@/assets/maps/imdf/interact/surface/1F.json";
import interact_surface_2F from "@/assets/maps/imdf/interact/surface/2F.json";
import interact_surface_3F from "@/assets/maps/imdf/interact/surface/3F.json";
import interact_surface from "@/assets/maps/imdf/interact/surface.json";
import studyhall_rooms_1F from "@/assets/maps/imdf/studyhall/rooms/1F.json";
import studyhall_rooms_2F from "@/assets/maps/imdf/studyhall/rooms/2F.json";
import studyhall_rooms_3F from "@/assets/maps/imdf/studyhall/rooms/3F.json";
import studyhall_rooms_4F from "@/assets/maps/imdf/studyhall/rooms/4F.json";
import studyhall_rooms_5F from "@/assets/maps/imdf/studyhall/rooms/5F.json";
import studyhall_stairs from "@/assets/maps/imdf/studyhall/stairs.json";
import studyhall_surface_1F from "@/assets/maps/imdf/studyhall/surface/1F.json";
import studyhall_surface_2F from "@/assets/maps/imdf/studyhall/surface/2F.json";
import studyhall_surface_3F from "@/assets/maps/imdf/studyhall/surface/3F.json";
import studyhall_surface_4F from "@/assets/maps/imdf/studyhall/surface/4F.json";
import studyhall_surface_5F from "@/assets/maps/imdf/studyhall/surface/5F.json";
import studyhall_surface from "@/assets/maps/imdf/studyhall/surface.json";
import studyhall_walkable_1F from "@/assets/maps/imdf/studyhall/walkable/1F.json";
import studyhall_walkable_2F from "@/assets/maps/imdf/studyhall/walkable/2F.json";
import studyhall_walkable_3F from "@/assets/maps/imdf/studyhall/walkable/3F.json";
import studyhall_walkable_4F from "@/assets/maps/imdf/studyhall/walkable/4F.json";
import studyhall_walkable_5F from "@/assets/maps/imdf/studyhall/walkable/5F.json";
import venue_venue from "@/assets/maps/imdf/venue/venue.json";

export const geoJsonMap = {
  address: {
    logicalId: "address",
    relativePath: "imdf/address.json",
    content: address as Feature<Geometry | null>,
  },
  interact_rooms_1F: {
    logicalId: "interact_rooms_1F",
    relativePath: "imdf/interact/rooms/1F.json",
    content: interact_rooms_1F as FeatureCollection,
  },
  interact_rooms_2F: {
    logicalId: "interact_rooms_2F",
    relativePath: "imdf/interact/rooms/2F.json",
    content: interact_rooms_2F as FeatureCollection,
  },
  interact_surface_1F: {
    logicalId: "interact_surface_1F",
    relativePath: "imdf/interact/surface/1F.json",
    content: interact_surface_1F as FeatureCollection,
  },
  interact_surface_2F: {
    logicalId: "interact_surface_2F",
    relativePath: "imdf/interact/surface/2F.json",
    content: interact_surface_2F as FeatureCollection,
  },
  interact_surface_3F: {
    logicalId: "interact_surface_3F",
    relativePath: "imdf/interact/surface/3F.json",
    content: interact_surface_3F as FeatureCollection,
  },
  interact_surface: {
    logicalId: "interact_surface",
    relativePath: "imdf/interact/surface.json",
    content: interact_surface as FeatureCollection,
  },
  studyhall_rooms_1F: {
    logicalId: "studyhall_rooms_1F",
    relativePath: "imdf/studyhall/rooms/1F.json",
    content: studyhall_rooms_1F as FeatureCollection,
  },
  studyhall_rooms_2F: {
    logicalId: "studyhall_rooms_2F",
    relativePath: "imdf/studyhall/rooms/2F.json",
    content: studyhall_rooms_2F as FeatureCollection,
  },
  studyhall_rooms_3F: {
    logicalId: "studyhall_rooms_3F",
    relativePath: "imdf/studyhall/rooms/3F.json",
    content: studyhall_rooms_3F as FeatureCollection,
  },
  studyhall_rooms_4F: {
    logicalId: "studyhall_rooms_4F",
    relativePath: "imdf/studyhall/rooms/4F.json",
    content: studyhall_rooms_4F as FeatureCollection,
  },
  studyhall_rooms_5F: {
    logicalId: "studyhall_rooms_5F",
    relativePath: "imdf/studyhall/rooms/5F.json",
    content: studyhall_rooms_5F as FeatureCollection,
  },
  studyhall_stairs: {
    logicalId: "studyhall_stairs",
    relativePath: "imdf/studyhall/stairs.json",
    content: studyhall_stairs as FeatureCollection,
  },
  studyhall_surface_1F: {
    logicalId: "studyhall_surface_1F",
    relativePath: "imdf/studyhall/surface/1F.json",
    content: studyhall_surface_1F as FeatureCollection,
  },
  studyhall_surface_2F: {
    logicalId: "studyhall_surface_2F",
    relativePath: "imdf/studyhall/surface/2F.json",
    content: studyhall_surface_2F as FeatureCollection,
  },
  studyhall_surface_3F: {
    logicalId: "studyhall_surface_3F",
    relativePath: "imdf/studyhall/surface/3F.json",
    content: studyhall_surface_3F as FeatureCollection,
  },
  studyhall_surface_4F: {
    logicalId: "studyhall_surface_4F",
    relativePath: "imdf/studyhall/surface/4F.json",
    content: studyhall_surface_4F as FeatureCollection,
  },
  studyhall_surface_5F: {
    logicalId: "studyhall_surface_5F",
    relativePath: "imdf/studyhall/surface/5F.json",
    content: studyhall_surface_5F as FeatureCollection,
  },
  studyhall_surface: {
    logicalId: "studyhall_surface",
    relativePath: "imdf/studyhall/surface.json",
    content: studyhall_surface as FeatureCollection,
  },
  studyhall_walkable_1F: {
    logicalId: "studyhall_walkable_1F",
    relativePath: "imdf/studyhall/walkable/1F.json",
    content: studyhall_walkable_1F as FeatureCollection,
  },
  studyhall_walkable_2F: {
    logicalId: "studyhall_walkable_2F",
    relativePath: "imdf/studyhall/walkable/2F.json",
    content: studyhall_walkable_2F as FeatureCollection,
  },
  studyhall_walkable_3F: {
    logicalId: "studyhall_walkable_3F",
    relativePath: "imdf/studyhall/walkable/3F.json",
    content: studyhall_walkable_3F as FeatureCollection,
  },
  studyhall_walkable_4F: {
    logicalId: "studyhall_walkable_4F",
    relativePath: "imdf/studyhall/walkable/4F.json",
    content: studyhall_walkable_4F as FeatureCollection,
  },
  studyhall_walkable_5F: {
    logicalId: "studyhall_walkable_5F",
    relativePath: "imdf/studyhall/walkable/5F.json",
    content: studyhall_walkable_5F as FeatureCollection,
  },
  venue_venue: {
    logicalId: "venue_venue",
    relativePath: "imdf/venue/venue.json",
    content: venue_venue as FeatureCollection,
  },
};

// オブジェクトのunion型定義
export type MapId = keyof typeof geoJsonMap;