#!/usr/bin/env node
/**
 * generate-geojson-registry.js
 *
 * manifest.json を読み、geojson を静的 import する registry js を生成する。
 *
 * usage:
 *   node ./scripts/generate_geojsonAssetMap.js
 */

import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// プロジェクトルートからの絶対パスを使用
const projectRoot = path.resolve(__dirname, "..");
const manifestPath = path.resolve(projectRoot, "assets/maps/manifest.json");
const outPath = path.resolve(
  projectRoot,
  "src/data/geojson/geojsonAssetMap.ts",
);

function toPosix(p) {
  return p.split(path.sep).join("/");
}

function makeIdentifier(base) {
  let id = base.replace(/[^a-zA-Z0-9_]/g, "_");
  if (!/^[a-zA-Z_]/.test(id)) id = "_" + id;
  return `${id}`;
}

function readManifest(p) {
  if (!fs.existsSync(p)) throw new Error(`manifest not found: ${p}`);
  const raw = fs.readFileSync(p, "utf8");
  return JSON.parse(raw);
}

function validIdentifier(s) {
  return /^[A-Za-z_$][A-Za-z0-9_$]*$/.test(s);
}

function generate(manifest) {
  if (!manifest.files || typeof manifest.files !== "object") {
    throw new Error("manifest.files is not found or invalid");
  }

  const imports = [];
  const mapEntries = [];
  const usedNames = new Set();

  const entries = Object.entries(manifest.files);

  for (const [logicalId, meta] of entries) {
    const relPath = meta.relativePath;
    if (!relPath) {
      console.warn(`skip ${logicalId}: no relativePath`);
      continue;
    }

    const importPath = `@/assets/maps/${toPosix(relPath)}`;

    let varName = makeIdentifier(logicalId);
    let counter = 1;
    while (usedNames.has(varName)) {
      varName = `${makeIdentifier(logicalId)}_${counter}`;
      counter++;
    }
    usedNames.add(varName);

    imports.push(`import ${varName} from "${importPath}";`);

    const key = validIdentifier(logicalId)
      ? logicalId
      : JSON.stringify(logicalId);

    if (logicalId === "address") {
      mapEntries.push(
        `  ${key}: {
    logicalId: ${JSON.stringify(logicalId)},
    relativePath: ${JSON.stringify(relPath)},
    content: ${varName} as Feature<Geometry | null>,
  },`,
      );
    } else {
      mapEntries.push(
        `  ${key}: {
    logicalId: ${JSON.stringify(logicalId)},
    relativePath: ${JSON.stringify(relPath)},
    content: ${varName} as FeatureCollection,
  },`,
      );
    }
  }

  const header = `/* THIS FILE IS AUTO-GENERATED BY scripts/generate-geojson-registry.js */
/* Do not edit by hand. */\n`;

  return [
    header,
    // JSでは型 import は不要
    // `import { ManifestFileEnrty } from "${manifestTypeImport}";`,
    `import type { Feature, FeatureCollection, Geometry } from "geojson"`,
    "",
    ...imports,
    "",
    `export const geoJsonMap = {`,
    ...mapEntries,
    `};`,
    "",
    "// オブジェクトのunion型定義",
    "export type MapId = keyof typeof geoJsonMap;",
  ].join("\n");
}

export async function generateGeojsonAssetMap() {
  try {
    const manifest = readManifest(manifestPath);
    const out = generate(manifest);
    fs.mkdirSync(path.dirname(outPath), { recursive: true });
    fs.writeFileSync(outPath, out, "utf8");
    console.log("Wrote registry to", outPath);
  } catch (e) {
    console.error(e.message || e);
    process.exit(1);
  }
}