import type { RoomCategory, ColorGroup } from "./types";

/** RoomCategory → ColorGroup マッピング */
export const ROOM_COLOR_GROUP: Record<RoomCategory, ColorGroup> = {
  learning: "blue",
  library: "olive",
  laboratory: "teal",
  prep: "gray",
  structure: "gray",
  meeting: "gold",
  staff: "gold",
  it: "teal",
  listening: "green",
  nursery: "pink",
  outdoor_space: "terrace",
  studio: "green",
  broadcasting: "amber",
  printing: "amber",
  music: "green",
  japanese: "brown",
  cooking: "coral",
  sewing: "coral",
  art: "brown",
  workshop: "orange",
  restroom: "cyan",
  vending: "indigo",
  changing: "indigo",
  elevator: "lime",
  waste: "gray",
  courtyard: "olive",
  terrace: "terrace",
};
